### ISSUE TITLE
snapshot stuck running the UITests

### ISSUE THREAD

**Issue by ilandbt** [fastlane/snapshot#399]
Every time i try to run snapshot it gets stuck in the same place.

log:

```
[12:06:23]: Running Tests: ▸ Touching Project.app
[12:06:23]: ▸ Building Project/ProjectTests [Debug]
[12:06:23]: ▸ Check Dependencies
[12:06:23]: ▸ Compiling ResetPasswordTests.swift
[12:06:23]: ▸ Compiling LoginTests.swift
[12:06:23]: ▸ Linking ProjectTests
[12:06:24]: ▸ ⚠️  ld: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/Developer/Library/Frameworks'
[12:06:24]: ▸ Generating 'ProjectTests.xctest.dSYM'
[12:06:24]: Running Tests: ▸ Touching ProjectTests.xctest
[12:06:24]: ▸ Build Succeeded
[12:06:24]: ▸ 2016-01-21 12:06:24.346 xcodebuild[10104:318512] [MT] IDETestOperationsObserverDebug: (D18F3A21-7384-4A86-9E34-0483F4F1FE38) Beginning test session D18F3A21-7384-4A86-9E34-0483F4F1FE38 with Xcode 7C68 on target <DVTiPhoneSimulator: 0x7f99de953d50> {
[12:06:24]: ▸ SimDevice: SimDevice : iPhone 4s (0B73B437-DF14-41CF-9CAD-D729D34DD24D) : state={ Shutdown } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-4s } runtime={ SimRuntime : 9.2 (13C75) - com.apple.CoreSimulator.SimRuntime.iOS-9-2 }
[12:06:24]: ▸ } (9.2 (13C75))
[12:06:24]: ▸ 2016-01-21 12:06:24.350 xcodebuild[10104:318512] [MT] IDETestOperationsObserverDebug: (99F08474-03AA-4BA1-A76A-134DC2D9AF99) Beginning test session 99F08474-03AA-4BA1-A76A-134DC2D9AF99 with Xcode 7C68 on target <DVTiPhoneSimulator: 0x7f99de953d50> {
[12:06:24]: ▸ SimDevice: SimDevice : iPhone 4s (0B73B437-DF14-41CF-9CAD-D729D34DD24D) : state={ Shutdown } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-4s } runtime={ SimRuntime : 9.2 (13C75) - com.apple.CoreSimulator.SimRuntime.iOS-9-2 }
[12:06:24]: ▸ } (9.2 (13C75))
[12:06:24]: ▸ Building Pods/AFNetworking [Debug]
[12:06:24]: ▸ Check Dependencies
[12:06:24]: ▸ Building Pods/SocketRocket [Debug]
[12:06:24]: ▸ Check Dependencies
[12:06:24]: ▸ Building Pods/MMProgressHUD [Debug]
[12:06:24]: ▸ Check Dependencies
[12:06:24]: ▸ Building Pods/RealtimeMessaging-iOS [Debug]
[12:06:24]: ▸ Check Dependencies
[12:06:24]: ▸ Building Pods/Pods [Debug]
[12:06:24]: ▸ Check Dependencies
[12:06:24]: ▸ Building Project/Project [Debug]
[12:06:24]: ▸ Check Dependencies
[12:06:24]: ▸ Running script 'Check Pods Manifest.lock'
[12:06:24]: ▸ Running script 'Copy Pods Resources'
[12:06:24]: ▸ Running script 'Embed Pods Frameworks'
[12:06:24]: ▸ Running script 'Run Script'
[12:06:24]: ▸ The run script is now located at ${PODS_ROOT}/Fabric/run'. To remove this warning, update your Run Script Build Phase to point to this new location.
[12:06:24]: ▸ Building Project/ProjectUITests [Debug]
[12:06:24]: ▸ Check Dependencies
[12:06:24]: ▸ Building Project/ProjectTests [Debug]
[12:06:24]: ▸ Check Dependencies
```

**Comment by tsafrir** [comment]
I have the same issue started yesterday on the same Xcode build as yours.
Also get stuck on iPhone4S, but on my logs the device state is "booted".
I also tried to reset simulators with `snaspshot reset_simulators` and restart the mac but it still get stuck when taking screenshots on iPhone4S.

**Comment by ilandbt** [comment]
The last update worked for me, but now i'm getting this:
```
Test Suite QuestUITests.xctest started


	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds

[11:44:05]: Exit status: 65
[11:44:05]: Tests failed - check out the log above
[11:44:05]: Backtrace:
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.5.0/lib/snapshot/error_handler.rb:14:in `handle_test_error'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.5.0/lib/snapshot/runner.rb:125:in `block in launch'
	/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.35.1/lib/fastlane_core/command_executor.rb:82:in `call'
	/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.35.1/lib/fastlane_core/command_executor.rb:82:in `execute'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.5.0/lib/snapshot/runner.rb:119:in `launch'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.5.0/lib/snapshot/runner.rb:35:in `block (3 levels) in work'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.5.0/lib/snapshot/runner.rb:31:in `each'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.5.0/lib/snapshot/runner.rb:31:in `block (2 levels) in work'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.5.0/lib/snapshot/runner.rb:30:in `each'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.5.0/lib/snapshot/runner.rb:30:in `block in work'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.5.0/lib/snapshot/runner.rb:29:in `each'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.5.0/lib/snapshot/runner.rb:29:in `work'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.53.0/lib/fastlane/actions/snapshot.rb:17:in `run'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.53.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.53.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.53.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.53.0/lib/fastlane/runner.rb:127:in `chdir'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.53.0/lib/fastlane/runner.rb:127:in `execute_action'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.53.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	Fastfile:68:in `block (2 levels) in parsing_binding'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.53.0/lib/fastlane/lane.rb:36:in `call'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.53.0/lib/fastlane/lane.rb:36:in `call'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.53.0/lib/fastlane/runner.rb:52:in `block in execute'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.53.0/lib/fastlane/runner.rb:46:in `chdir'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.53.0/lib/fastlane/runner.rb:46:in `execute'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.53.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.53.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.53.0/bin/fastlane:37:in `block (2 levels) in run'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.53.0/bin/fastlane:149:in `run'
	/Library/Ruby/Gems/2.0.0/gems/fastlane-1.53.0/bin/fastlane:155:in `<top (required)>'
	/usr/local/bin/fastlane:23:in `load'
	/usr/local/bin/fastlane:23:in `<main>'

+----------+---------+
|  snapshot results  |
+----------+---------+
| Device   | en-US   |
+----------+---------+
| iPhone 6 |  ❌      |
+----------+---------+

[11:44:05]: Variable Dump:
[11:44:05]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios test"}
[11:44:05]: Tests failed - check out the log above
```

But i have 1 test:

``` Swift
import XCTest

class QuestUITests: XCTestCase {
        
    override func setUp() {
        super.setUp()
        
        // Put setup code here. This method is called before the invocation of each test method in the class.
        
        // In UI tests it is usually best to stop immediately when a failure occurs.
        continueAfterFailure = true
        // UI tests must launch the application that they test. Doing this in setup will make sure it happens for each test method.
        let app = XCUIApplication()
        setupSnapshot(app)
        app.launch()

        // In UI tests it’s important to set the initial state - such as interface orientation - required for your tests before they run. The setUp method is a good place to do this.
    }
    
    override func tearDown() {
        // Put teardown code here. This method is called after the invocation of each test method in the class.
        super.tearDown()
    }
    
    func testExample() {
        snapshot("0Launch")
        // Use recording to get started writing UI tests.
        // Use XCTAssert and related functions to verify your tests produce the correct results.
    }
    
}
```

**Comment by muZZkat** [comment]
I get the same but only for the iPhone 6,6s, 6 Plus and 6s Plus simulator... other simulators are working OK. I have verbose enabled but don't see anything, is there other logs? 

I've updated to the latest snapshot and still see the same thing.

**Comment by muZZkat** [comment]
Turns out my Test target was only configured for armv7, not sure why but switching it to standard arch fixed it.

**Comment by jeffreyjackson** [comment]
This just started happening for me as well.  For whatever reason, snapshot has begun to hang on 'check dependencies'

**Comment by jeffreyjackson** [comment]
I was able to resolve this by checking `locale` and realizing `LC_ALL` wasn't set to `en_US.UTF-8`

**Comment by ened** [comment]
@jeffreyjackson could you elaborate on this?
