### ISSUE TITLE
snapshot crashes during "Collecting screenshots…" phase

### ISSUE THREAD

**Issue by ashur** [fastlane/snapshot#419]
## Description

Whether running `snapshot` directly or as a `fastlane` action, snapshot crashes with `undefined method 'last' for nil:NilClass` after successfully executing the single test and starting the "Collecting screenshots…" phase:

```
▸ Test Succeeded
▸ Selected tests
▸ Test Suite UITests.xctest started
▸ ScreenshotTests
▸ ✓ testiPhoneScreenshots (8.353 seconds)
▸ 	 Executed 1 test, with 0 failures (0 unexpected) in 8.353 (8.355) seconds
▸ 
Collecting screenshots...
undefined method `last' for nil:NilClass
Backtrace:
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/collector.rb:59:in `block (6 levels) in attachments'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/collector.rb:56:in `each'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/collector.rb:56:in `block (5 levels) in attachments'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/collector.rb:55:in `each'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/collector.rb:55:in `block (4 levels) in attachments'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/collector.rb:54:in `each'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/collector.rb:54:in `block (3 levels) in attachments'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/collector.rb:53:in `each'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/collector.rb:53:in `block (2 levels) in attachments'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/collector.rb:52:in `each'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/collector.rb:52:in `block in attachments'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/collector.rb:51:in `each'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/collector.rb:51:in `attachments'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/collector.rb:9:in `fetch_screenshots'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/runner.rb:140:in `launch'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/runner.rb:35:in `block (3 levels) in work'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/runner.rb:31:in `each'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/runner.rb:31:in `block (2 levels) in work'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/runner.rb:30:in `each'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/runner.rb:30:in `block in work'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/runner.rb:29:in `each'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/runner.rb:29:in `work'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/bin/snapshot:37:in `block (2 levels) in run'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/bin/snapshot:78:in `run'
	/Library/Ruby/Gems/2.0.0/gems/snapshot-1.6.0/bin/snapshot:84:in `<top (required)>'
	/usr/local/bin/snapshot:23:in `load'
	/usr/local/bin/snapshot:23:in `<main>'
```

### fastlane

| Version |
| :-: |
| 1.57.0 |

**Fastfile**:
```
default_platform :ios

platform :ios do
	desc "Sets up and takes screenshots"
	lane :screenshots do
		snapshot(
			scheme: "Snapshot",
			ios_version: "9.2",
			devices: ["iPhone 6"],
			languages: ["en-US"]
		)
	end
end
```

### snapshot

| Version |
| :-: |
| 1.6.0 |

**Snapfile**:
```
devices([
	"iPhone 6"
])

languages([
	"en-US"
])

scheme "Snapshot"
```

## Test File

An incredibly barebones test: launch and take a screenshot...

```Swift
import XCTest

class ScreenshotTests: XCTestCase
{
	override func setUp()
	{
		super.setUp()
		continueAfterFailure = false

		// for snapshot https://github.com/fastlane/snapshot
		let app = XCUIApplication()
		setupSnapshot(app)
		app.launch()
	}

	override func tearDown()
	{
		super.tearDown()
	}

	func testiPhoneScreenshots()
	{
		snapshot("01Servers")
	}
}
```

Note: the `SnapshotHelper.swift` file _has_ already been added to the UITests target

**Comment by KrauseFx** [comment]
Could you run it again using `--verbose`, then you should see the path to the plist file. Could you share the content of the file?

**Comment by ashur** [comment]
Ah… I was inadvertently running against Xcode 7.3b's command line tools. Switching back to 7.2 via `xcode-select` seems to have done the trick. If the .plist contents are still helpful for troubleshooting 7.3, I'd be happy to post it.

**Comment by KrauseFx** [comment]
Interesting, that means  has changed something in the new Xcode version, could you send it to me? In case there is any sensitive information, feel free to send it to me via email instead, thank you :+1:

**Comment by dive** [comment]
@KrauseFx Yep. I can confirm that this issue is reproducible only with Xcode 7.3 beta (b4 as well). No problem with Snapshot if I use Xcode 7.2 with the same configuration.

**Comment by ZevEisenberg** [comment]
@KrauseFx I'm having the same problem, and I can't run with the Xcode 7.2 command line tools because I've already updated my project with the Xcode 7.3 beta Swift breaking changes. Happy to send any info that could help you debug.

**Comment by ZevEisenberg** [comment]
Oh, and my stack trace is a bit shallower:

```[17:29:05]: Collecting screenshots...
[17:29:05]: undefined method `last' for nil:NilClass

+----------+---------+
|  snapshot results  |
+----------+---------+
| Device   | en-US   |
+----------+---------+
| iPhone 6 |  ❌      |
+----------+---------+

Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'b38e335c4445a2a111398a5863f0fa08'
The crash report has been stored locally '/tmp/sentry_b38e335c4445a2a111398a5863f0fa08.json'
/Users/igeek/.rvm/gems/ruby-2.2.3/gems/snapshot-1.10.0/lib/snapshot/runner.rb:52:in `work': [!] undefined method `last' for nil:NilClass (RuntimeError)
	from /Users/igeek/.rvm/gems/ruby-2.2.3/gems/snapshot-1.10.0/bin/snapshot:37:in `block (2 levels) in run'
	from /Users/igeek/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/igeek/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/igeek/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/igeek/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/igeek/.rvm/gems/ruby-2.2.3/gems/fastlane_core-0.36.8/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/igeek/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/igeek/.rvm/gems/ruby-2.2.3/gems/snapshot-1.10.0/bin/snapshot:78:in `run'
	from /Users/igeek/.rvm/gems/ruby-2.2.3/gems/snapshot-1.10.0/bin/snapshot:84:in `<top (required)>'
	from /Users/igeek/.rvm/gems/ruby-2.2.3/bin/snapshot:23:in `load'
	from /Users/igeek/.rvm/gems/ruby-2.2.3/bin/snapshot:23:in `<main>'
	from /Users/igeek/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/igeek/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by ZevEisenberg** [comment]
And if my test summaries are helpful: http://cl.ly/fGan
